name: Deploy Lambda Function for text detection 

on:
  push:
    branches:
      - develop
    paths:
      - 'code/image-processing/rekognition_function.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Zip Lambda function
        working-directory: code/image-processing
        run: |
          zip -r rekognition_function.zip rekognition_function.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function
        working-directory: code/image-processing
        run: |
          aws lambda update-function-code \
            --function-name rekognition_function \
            --zip-file fileb://rekognition_function.zip \
            --publish
